package com.github.royalfamily.vagan.util


const val NETWORK_BASE_NAME_URL = "NETWORK_BASE_NAME_URL"
const val NETWORK_BASE_NAME_RETROFIT = "NETWORK_BASE_NAME_RETROFIT"
const val NETWORK_BASE_NAME_SERVICE = "NETWORK_BASE_NAME_SERVICE"

const val NETWORK_REMOTE_DATA_SOURCE = "NETWORK_BASE_NAME_SERVICE"

const val NETWORK_URL_NAME_KAKAO = "NETWORK_URL_NAME_KAKAO"
const val NETWORK_TYPE_NAME_KAKAO = "NETWORK_TYPE_NAME_KAKAO"